config/routes.rb
Wifindr::Application.routes.draw do
  resources :saved_networks
  # resources :homes
  root to: "homes#index"

  devise_for :users, controllers: {registrations: :users}
  # devise_for :users, :controllers => { :registrations => "registrations" }

  devise_scope :user do
    resources :users, only: [:index, :show] do
      member do
        get :befriend
      end
    end
  end


  resources :friendships, only: [] do
    member do
      get :accept
      get :reject
    end
  end

end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable, :confirmable,
         :recoverable, :rememberable, :trackable, :validatable, :timeoutable, :confirm_within => 10.minutes

  # Setup accessible (or protected) attributes for your model
  attr_accessible :email, :password, :password_confirmation, :remember_me, :name
  validates :name, presence: true

  has_many :saved_networks

  has_many :friendships
  has_many :friends,
              through:    :friendships,
              class_name: 'User',
              conditions: "accepted = true"

  has_many :pending_friend_invites_sent,
              class_name: 'Friendship',
              conditions: "accepted IS NULL"

  has_many :rejected_friend_invites_sent,
              class_name: 'Friendship',
              conditions: "accepted = false"

  has_many :pending_friend_invites_received,
              class_name:  'Friendship',
              foreign_key: :friend_id,
              conditions:  "accepted IS NULL"

  has_many :rejected_friend_invites_received,
              class_name:  'Friendship',
              foreign_key: :friend_id,
              conditions:  "accepted = false"

  has_many :accepted_friend_invites_received,
              class_name:  'Friendship',
              foreign_key: :friend_id,
              conditions:  "accepted = true"
  # def invite_pending?(user)
  #   puts "pending -> #{pending_friend_invites_sent}"
  #   rst = pending_friend_invites_sent.map(&:user_id)
  # end

  def is_friends_with?(other_user)
    friendships.where(friend_id: other_user.id, accepted: true).count > 0
  end

  before_save :set_default_role

  def role? role
  	self.role.to_s == role.to_s
  end

  def set_default_role
  	if self.role.nil?
  		self.role = "user"
  	end
  end
end




# friendships both foreign keys pointing t the user table
# two different names
# join model lets call friender and friendee
# has one friender, class name user
# has one friendee, class name user

# user model has many friends as friender
# user model has many friends as friendee

# make a method that lists all the users
# add boolean accept/reject >> way to confirm a friendships
# add migration to

app/controllers/users_controller.rb
class UsersController < Devise::RegistrationsController
  before_filter :authenticate_user!

  def index
    if user_signed_in?
      @users = User.all
      @friends = current_user.friends
    else
      redirect_to new_user_session_path, notice: "You need to sign in or sign up before continuing."
    end
  end

  def show
    if user_signed_in?
      @user = User.find params[:id]
      @invites = @user.pending_friend_invites_received.includes(:user)
      @friends = current_user.friends
    else
      redirect_to new_user_session_path, notice: "You need to sign in or sign up before continuing."
    end
  end

  def befriend
    if user_signed_in?
    @user = User.find params[:id]
    Friendship.create!(user: current_user, friend: @user)
    flash[:notice] = "Invite sent"
    redirect_to saved_networks_path
  else
    redirect_to new_user_session_path, notice: "You need to sign in or sign up before continuing."
    end
  end

end

app/views/users/index.html.haml
.container
  .row
    .col-md-6
      .page-header
        %h1 All Users
      #table-responsive
        %table{class: "table table-striped table-hover"}
          %tr
            %th Name
            %th Email
            %th Friendship
            - @users.each do |user|
              - unless user == current_user
                %tr
                  %td= user.name
                  %td= user.email
                  - if user.is_friends_with?(current_user)
                    %td
                      %button.btn.btn-default.btn-block{disabled: "disabled", type: "button"} Friends
                  - else
                    %td
                      = link_to "Add Friend", befriend_user_path(user), class: "btn btn-primary btn-block", type: "button"
  %br/

app/views/users/show.html.haml
.container
  .row
    .col-md-6
      .page-header
        %h1 Friends
      #table-responsive
        %table{class: "table table-striped table-hover"}
          %tr
          - if @user == current_user && @friends.present?
            %th Name
            %th Email
            - @friends.each do |friend|
              %tr
                %td= friend.name
                %td= friend.email
          - else
            %td No Friends!
      %h2 Pending Invites
      #table-responsive
        %table{class: "table table-striped table-hover"}
          %tr
          - if @user == current_user && @invites.present?
            %th Invitee
            %th Action
            %th
            - @invites.each do |invite|
              %tr
                %td
                  = invite.user.name
                %td
                  = link_to "Accept", accept_friendship_path(invite), class: "btn btn-default btn-block"
                %td
                  = link_to "Reject", reject_friendship_path(invite), class: "btn btn-danger btn-block"
          - else
            %td No Invites