config/routes.rb
Wifindr::Application.routes.draw do
  resources :saved_networks
  # resources :homes
  root to: "homes#index"

  devise_for :users, controllers: {registrations: :users}
  # devise_for :users, :controllers => { :registrations => "registrations" }

  devise_scope :user do
    resources :users, only: [:index, :show] do
      member do
        get :befriend
      end
    end
  end


  resources :friendships, only: [] do
    member do
      get :accept
      get :reject
    end
  end

end

app/models/saved_network.rb
class SavedNetwork < ActiveRecord::Base
  attr_accessible :address, :latitude, :longitude, :public, :security_type, :wifi_name, :wifi_pw, :image

  belongs_to :user

  geocoded_by :address
  validates :address, presence: true
  validates :wifi_name, presence: true



  after_validation :geocode, if: ->(obj){ obj.address.present? and obj.address_changed? }

  def self.friends_networks(user)
    user.friends.map do |friend|
      friend.saved_networks
    end.flatten
  end
end

app/controllers/saved_networks_controller.rb
class SavedNetworksController < ApplicationController
  before_filter :authenticate_user!
  include SavedNetworksHelper
  # GET /saved_networks
  # GET /saved_networks.json
  def index
    @saved_networks = current_user.saved_networks
    @friends_networks = SavedNetwork.friends_networks(current_user)
    @markers = build_markers @saved_networks, "31708f"
    @friends_markers = build_markers @friends_networks, "f5f5f5"
    gon.markers = @markers
    gon.friends_markers = @friends_markers
    respond_to do |format|
      format.html # index.html.erb
      format.json { render json: @saved_networks }
    end
  end

  # GET /saved_networks/1
  # GET /saved_networks/1.json
  def show
    @saved_network = SavedNetwork.find(params[:id])

    respond_to do |format|
      format.html # show.html.erb
      format.json { render json: @saved_network }
    end
  end

  # GET /saved_networks/new
  # GET /saved_networks/new.json
  def new
    @saved_network = SavedNetwork.new
    respond_to do |format|
      format.html # new.html.erb
      format.json { render json: @saved_network }
    end
  end

  # GET /saved_networks/1/edit
  def edit
    @saved_network = SavedNetwork.find(params[:id])
  end

  # POST /saved_networks
  # POST /saved_networks.json
  def create
    @saved_network = current_user.saved_networks.new(params[:saved_network])

    respond_to do |format|
      if @saved_network.save
        format.html { redirect_to @saved_network, notice: 'Saved network was successfully created.' }
        format.json { render json: @saved_network, status: :created, location: @saved_network }
      else
        format.html { render action: "new" }
        format.json { render json: @saved_network.errors, status: :unprocessable_entity }
      end
    end
  end

  # PUT /saved_networks/1
  # PUT /saved_networks/1.json
  def update
    @saved_network = SavedNetwork.find(params[:id])

    respond_to do |format|
      if @saved_network.update_attributes(params[:saved_network])
        format.html { redirect_to @saved_network, notice: 'Saved network was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: "edit" }
        format.json { render json: @saved_network.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /saved_networks/1
  # DELETE /saved_networks/1.json
  def destroy
    @saved_network = SavedNetwork.find(params[:id])
    @saved_network.destroy

    respond_to do |format|
      format.html { redirect_to saved_networks_url }
      format.json { head :no_content }
    end
  end

private
  def build_markers networks, color
    Gmaps4rails.build_markers(networks) do |network, marker|
      marker.lat(network.latitude)
      marker.lng(network.longitude)
      marker.infowindow(marker_legend(network))
      marker.picture({
        :url => "http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=|#{color}|000000",
        :width   => 32,
        :height  => 32
        })
    end
  end
end

app/helpers/saved_networks_helper.rb
module SavedNetworksHelper
  include ActionView::Helpers::TagHelper
  def marker_legend data
    [content_tag(:h4, "Network Name: "), content_tag(:h3, data.wifi_name), content_tag(:h4, "Network Password: "), content_tag(:h3, data.wifi_pw)].join
  end
end

app/views/saved_networks/_form.html.haml
= form_for @saved_network, role: "form" do |f|
  - if @saved_network.errors.any?
    #error_explanation
      .alert.alert-warning.alert-dismissable
        %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} &#215;
        - @saved_network.errors.full_messages.each do |msg|
          %p
          = msg
  .field.form-group
    = f.label :latitude, 'Latitude'
    %br/
    = f.text_field :latitude, readonly: true, class: 'form-control'
  .field.form-group
    = f.label :longitude, 'Longitude'
    %br/
    = f.text_field :longitude, readonly: true, class: 'form-control'
  .field.form-group
    = f.label :address, 'Full Address'
    %br/
    = f.text_field :address, class: 'form-control'
  .field.form-group
    = f.label :wifi_name, 'Network Name'
    %br/
    = f.text_field :wifi_name, class: 'form-control'
  .field.form-group
    = f.label :wifi_pw, 'Network Password'
    %br/
    = f.text_field :wifi_pw, class: 'form-control'
  .field.form-group
    = f.label :image, 'Image'
    %br/
    = f.file_field :image, {type: "file", capture: "camera", accept: "image/*", id:"cameraInput"}
  .field.form-group
    = f.label :security_type, 'Security Type'
    %br/
    = f.select :security_type, options_for_select(["None", "WPA", "WPA/2", "WEP", "802.1X"]), {}, {class: "form-control"}
  .actions.form-group
    = f.submit 'Save', class: "btn btn-primary btn-lg btn-block"

app/views/saved_networks/edit.html.haml
.container
  .row
    .col-md-6
      .page-header
        %h1 Edit Network
      = render 'form'
      = link_to 'Back', saved_networks_path, class: "btn btn-default btn-block", type: "button"

app/views/saved_networks/index.html.haml
.container
  .row
    .col-md-12
      .page-header
        %h1 All Locations
      #map{style: "width: 100%; height: 400px;"}
      %br/
    .col-md-4
      = link_to 'New Network', new_saved_network_path, class: "btn btn-primary btn-lg btn-block", type: "button"
      %h6
        %span.glyphicon.glyphicon-asterisk
        = image_tag "http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=|31708f|000000"
        \= Your networks
        = image_tag "http://chart.apis.google.com/chart?chst=d_map_pin_letter&chld=|f5f5f5|000000"
        \= Friends Networks
  .row
    .col-md-6
      %h2 My Networks
      #table-responsive
        %table{class: 'table table-striped table-hover', name: "t"}
          %tbody
            %tr
              %th SSID
              %th Password
              %th Address
              %th Actions
            - @saved_networks.each do |saved_network|
              %tr
                %td= saved_network.wifi_name
                %td= saved_network.wifi_pw
                %td= saved_network.address
                %td.dropdown
                  %button{type: 'button', class: "btn btn-default dropdown-toggle btn-block", "data-toggle" => "dropdown"}
                    %b.caret
                  %ul.dropdown-menu{role: 'menu'}
                    %li
                      = link_to 'Show', saved_network
                    %li
                      = link_to 'Edit', edit_saved_network_path(saved_network)
                    %li
                      = link_to 'Delete', saved_network, :method => :delete, :data => { :confirm => 'Are you sure?' }
    .col-md-6
      %h2 Friends Networks
      #table-responsive
        %table{class: 'table table-striped table-hover'}
          %tbody
            %tr
              %th Creator
              %th SSID
              %th Password
              %th Address
            - @friends_networks.each do |friends_network|
              %tr
                %td= friends_network.user.name
                %td= friends_network.wifi_name
                %td= friends_network.wifi_pw
                %td= friends_network.address
  %br/

app/views/saved_networks/new.html.haml
.container
  .row
    .col-md-6
      .page-header
        %h1 New Network
      = render 'form'
      = link_to 'Back', saved_networks_path, class: "btn btn-default btn-block", type: "button"

app/views/saved_networks/show.html.haml
.container
  .row
    .col-md-3.col-md-offset-1
      %p
        %h3 Network Name:
        %h4
          = @saved_network.wifi_name
      %p
        %h3 Network Password:
        %h4
          = @saved_network.wifi_pw
      %p
        %h3 Address:
        %h4
          = @saved_network.address
      %p
        %h3 Security Type:
        %h4
          = @saved_network.security_type
      %p
        %h3 Latitude:
        %h4
          = @saved_network.latitude
      %p
        %h3 Longitude:
        %h4
          = @saved_network.longitude
      = link_to 'Edit', edit_saved_network_path(@saved_network), class: "btn btn-primary btn-block", type: "button"
      = link_to 'Back', saved_networks_path, class: "btn btn-default btn-block", type: "button"

    .col-md-6.col-md-offset-1
      = image_tag "http://maps.google.com/maps/api/staticmap?size=500x350&sensor=false&zoom=16&markers=#{@saved_network.latitude}%2C#{@saved_network.longitude}"
      %h3 Nearby Locations
      %ul
      - for saved_network in @saved_network.nearbys(10)
        %li
          = link_to saved_network.address, saved_network
          (#{saved_network.distance.to_f.round(2)} miles)