config/routes.rb
Wifindr::Application.routes.draw do
  resources :saved_networks
  # resources :homes
  root to: "homes#index"

  devise_for :users, controllers: {registrations: :users}
  # devise_for :users, :controllers => { :registrations => "registrations" }

  devise_scope :user do
    resources :users, only: [:index, :show] do
      member do
        get :befriend
      end
    end
  end


  resources :friendships, only: [] do
    member do
      get :accept
      get :reject
    end
  end

end

app/views/layouts/application.html.haml
!!!
%html
  %head
    %title WiFiNDR
    %script{src: "//maps.google.com/maps/api/js?v=3.13&sensor=false&libraries=geometry", type: "text/javascript"}
    %script{src: "//google-maps-utility-library-v3.googlecode.com/svn/tags/markerclustererplus/2.0.14/src/markerclusterer_packed.js", type: "text/javascript"}
    %link{href: "http://fonts.googleapis.com/css?family=Lato:300", rel: "stylesheet", type: "text/css"}/
    = include_gon
    = stylesheet_link_tag    "application", :media => "all"
    = javascript_include_tag "application"
    = csrf_meta_tags
    %meta{content: "width=device-width, initial-scale=1, maximum-scale=1, user-scalable=no", name: "viewport"}
  %body
    %nav{class: "navbar navbar-default navbar-fixed-top", role: "navigation"}
      .container-fluid
        .navbar-header
          %button.navbar-toggle{"data-target" => "#bs-example-navbar-collapse-1", "data-toggle" => "collapse", type: "button"}
            %span.sr-only Toggle navigation
            %span.icon-bar
            %span.icon-bar
            %span.icon-bar
          = link_to 'WiFiNDR', root_path, class: 'navbar-brand glyphicon glyphicon-map-marker'
        #bs-example-navbar-collapse-1.collapse.navbar-collapse
          %ul.nav.navbar-nav
            %li
              = link_to 'Networks', saved_networks_path
            %li
              = link_to 'Users', users_path
            - if user_signed_in?
              %li
                = link_to 'Friends', user_path(current_user)

          %ul.nav.navbar-nav.navbar-right
            - if user_signed_in?
              %li.dropdown
                %a.dropdown-toggle{"data-toggle" => "dropdown", href: "#"}
                  = current_user.email
                  %b.caret
                %ul.dropdown-menu
                  %li
                    = link_to 'Logout', destroy_user_session_path, method: 'delete'
                  %li
                    = link_to 'Edit Profile', edit_user_registration_path
            - else
              %li
                = link_to 'Login', new_user_session_path
              %li
                = link_to 'Sign Up', new_user_registration_path
    .container
      -flash.each do |name, message|
        %div{class: "alert alert-info alert-dismissable"}
          %button.close{"aria-hidden" => "true", "data-dismiss" => "alert", type: "button"} &#215;
          = message
    = yield

    %nav.navbar.navbar-default.navbar-fixed-bottom{role: "navigation"}
      .container
        %h5
          %span.glyphicon.glyphicon-copyright-mark
          2014 for General Assembly, London